config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :events
  get '/festivals', to: 'events#festival', as: 'festivals'
  get '/arts', to: 'events#art', as: 'arts'
  get '/cons', to: 'events#con', as: 'cons'
  get '/concerts', to: 'events#concert', as: 'concerts'
  resources :users, only: [:new, :create]

  root 'events#index'

end

app/views/art_events/_form.html.erb
<!-- Alerts users if there are any errors in the form -->
<% if @artevent.errors.any? %>
	<h2><%= pluralize(@artevent.errors.count, "error") %>
	<ul class="list-group">
		<% @artevent.errors.messages.each do |message| %>
		<li class="list-group-item list-group-item-danger">
			<%= message[1][0] %>
		</li>
	<% end %>
	</ul> 
<% end %>

<%= bootstrap_form_for @artevent do |f| %>
<div class="row">
	<!-- Two column form with Bootstrap -->
  <div class="col-md-6">
  	<!-- Makes it easier to style each part of the form with Bootstrap -->
  	<div class="form-group">
			<%= f.text_field :name, placeholder: 'Name', label: "Event Name *" %>
		</div>
  	<div class="form-group">
			<%= f.date_select :event_date, label: 'Event Date' %>
		</div>
		<!-- Time-field allows you to select hour, minute and AM/PM in one box -->
		<div class="form-inline form-group">
			<%= f.time_field :start_time, {ampm: true, minute_step: 15} %>
			<%= f.time_field :end_time, {ampm: true, minute_step: 15} %>
		</div>
  	<div class="form-group">
			<%= f.text_area :details, {size: "30x7"} %>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
		<%= f.text_field :price, placeholder: 'Price', label: "Price *" %>
		</div>
		<!-- Drop down menu to select neighborhood from neighborhood model -->
  	<div class="form-group">
			<%= f.label "Neighborhood:" %>
			<%= collection_select :art_event, :neighborhood, Neighborhood.all, :id, :name %>
		</div>
  	<div class="form-group">
			<%= f.text_field :street, placeholder: 'Street Address', label: 'Address *' %>
		</div>
  	<div class="form-group">
			<%= f.text_field :city, placeholder: 'City', label: 'City *' %>
		</div>
  	<div class="form-group">	
			<%= f.text_field :state, :value => 'CA', label: 'State *' %>
		</div>
  	<div class="form-group">
			<%= f.text_field :zip, placeholder: 'Zip Code', label: 'Zip Code *' %>
		</div>
		<%= f.submit "Submit" %>
		<% end %>
		<!-- Back arrow -->
		<span class="spaced glyphicon glyphicon-chevron-left"></span>
		<%= link_to "	Back to the Art Events Page", art_events_path %>
	</div>
</div>

app/views/art_events/edit.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default art_nav nav_img">  
	<%= render partial: "shared/navbar" %>
</nav>

<div class="container">
	<!-- Flash alerts -->
	<%= render partial: "shared/flash" %>

	<!-- Header specifically for updating event (vs. creating) -->
	<h1 class="header">Update This Event</h1>

	<!-- Form for editing or creating events -->
	<%= render partial: "form" %>
</div>

app/views/art_events/new.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default art_nav nav_img"> 
	<%= render partial: "shared/navbar" %>
</nav>

<div class="container">
	<!-- Flash alert -->
	<%= render partial: "shared/flash" %>

	<!-- Header that is specific to create (vs. update) -->
	<h1 class="header">New Art Event</h1>

	<!-- Form for create and update -->
	<%= render partial: "form" %>
</div>

app/views/art_events/show.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default art_nav nav_img"> 
  <%= render partial: "shared/navbar" %>
</nav>

<!-- Flash alert -->
<%= render partial: "shared/flash" %>

<div class="container">
  <h1 class="header"><%= @artevent.name %></h1>
  <div class="row show_text">
    <!-- Two column layout with Bootstrap -->
    <div class="col-md-6 show_col_1">
      <!-- Back arrow and link to the main art events page -->
      <span class="glyphicon glyphicon-chevron-left"></span>
      <%= link_to " Back to the Art Events Page", art_events_path %>
      <br><br>
      <p class="bold inline">Date:  </p>
      <%= @artevent.event_date.strftime("%m/%d/%y")%>
      <br><br>
      <p class="bold inline">Time:  </p>
      <%= @artevent.start_time.strftime("%l:%M%p") %> - <%= @artevent.end_time.strftime("%l:%M%p") %>
      <br><br>
      <p class="bold">Address:</p> 
      <%= @artevent.street %>, <%= @artevent.city %>, <%= @artevent.state %>, <%= @artevent.zip %>
      <br><br>
      <% if @artevent.details != "" %>
        <p class="bold">Details:</p>
        <%= @artevent.details %>
      <% end %>
      <br><br>
      <!-- If the event has been updated at some point, it will show the username of the last person who updated it -->
      <% if @artevent.updated_by_id != nil %>
        <em>Last updated by:</em>
        <%= @artevent.updated_by_id %>
      <% end %>
      <!-- For styling purposes, only shows the ~ if both Last Updated by and Created by are being shown -->
      <!-- Otherwise there is nothing or only one of them on the line -->
      <% if @artevent.updated_by_id != nil && @artevent.created_by_id != nil %>
        ~ 
      <% end %>
      <!-- If someone created this event (not seeded), their username will be displayed here -->
      <% if @artevent.created_by_id != nil %>
        <em>Created by:</em> 
        <%= @artevent.created_by_id %>
      <% end %>
      <br><br>
      <%= link_to "Update This Event", edit_art_event_path(@artevent) %>
      <br><br>
      <!-- Hides the delete button unless user is the admin -->
      <% if current_user %>
        <% if current_user.is_admin? %>
          <%= link_to "Delete This Event", @artevent, method: :delete, data: { confirm: 'Are you sure you want to delete this artevent?' } %>
        <% end %>
      <% end %>
    </div>
    <!-- Second column -->
    <div class="col-md-6" style='width: 400px;'>
      <div id="map" style='width: 400px; height: 400px;'></div>
    </div>
  
  <!-- Google Maps API -->
  <script type ="text/javascript">
  	var handler = Gmaps.build('Google');
    // Sets the zoom, your API key
    handler.buildMap({ provider: {zoom: 14, provider_key: "AIzaSyBnugBXbtHJ6qqIyILKqKPQ1l2rafKtjx0"}, internal: {id: 'map'}}, function(){
    // Adds markers to the event based on the coordinates that Geocoder made with the art event's combined address
    // Latitude and longitude are reversed in the Mongo db
    markers = handler.addMarker(
      {
        lat: <%= @artevent.to_coordinates[0] %>,
        lng: <%= @artevent.to_coordinates[1] %>
      }
    );
    // Tells the map to center on those coordinates
    handler.map.centerOn({
        lat: <%= @artevent.to_coordinates[0] %>,
        lng: <%= @artevent.to_coordinates[1] %>
      });
  });
  </script>
</div>