config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :events
  get '/festivals', to: 'events#festival', as: 'festivals'
  get '/arts', to: 'events#art', as: 'arts'
  get '/cons', to: 'events#con', as: 'cons'
  get '/concerts', to: 'events#concert', as: 'concerts'
  resources :users, only: [:new, :create]

  root 'events#index'

end

app/views/shared/_flash.html.erb
<!-- Flashes green notice for success (via Bootstrap)-->
<% if flash[:success] %>
  <% flash.each do |key, value| %>
    <div class="alert alert-success">
      <%= value %>
    </div>
  <% end %>
<% end %>

<!-- Flashes red notice for errors (via Bootstrap) -->
<% if flash[:error] %>
  <% flash.each do |key, value| %>
    <div class="alert alert-error">
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-fluid nav_text">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <!-- The button that appears when the navbar collapses; when toggled, shows the non-header links in a dropdown section -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- The header appears in both mobile and desktop versions -->
    <h1 class="nav_logo">L.A. Events</h1>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class "nav navbar-nav nav_links_all">
      <li class="nav_links"><%= link_to "All Events", events_path, :class => 'nav_link_color' %></li>
      <li class="nav_links"><%= link_to "Festivals", festivals_path, :class => 'nav_link_color' %></li>
      <li class="nav_links"><%= link_to "Art", arts_path, :class => 'nav_link_color' %></li>
      <li class="nav_links"><%= link_to "Concerts", concerts_path, :class => 'nav_link_color' %></li>
      <li class="nav_links"><%= link_to "Geek", cons_path, :class => 'nav_link_color' %></li>
      <% if current_user %>
        <li><%= link_to "Sign Out", sessions_path, :method => :delete, :class => "nav_sign_out" %></li>
      <% else %>
        <li><%= link_to "Sign In", new_sessions_path, :class => "nav_sign_out" %></li>
      <% end %>
      </ul>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

app/views/shared/home.html.erb
<!-- Main postcard-style image -->
<img src="../assets/welcome.jpg" id="home_img" class="img-responsive center-block" ></img>

<!-- Text that is positioned over the image and restyled as the page collapses -->
<div class="home_text_div">
	 <h1 id="home_logo">L.A. Events</h1>

	 <p class="home_sign_in_up"><%= link_to "Sign Up", new_user_path, :class => "home_link" %> ~ <%= link_to "Sign In", new_sessions_path, :class => "home_link" %></p>
</div>

<!-- Stays at the bottom center of the page at any size screen -->
<p class="created_by">Created by Kelsey Ledford and Jojo Estrada</p>