config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :events
  get '/festivals', to: 'events#festival', as: 'festivals'
  get '/arts', to: 'events#art', as: 'arts'
  get '/cons', to: 'events#con', as: 'cons'
  get '/concerts', to: 'events#concert', as: 'concerts'
  resources :users, only: [:new, :create]

  root 'events#index'

end

app/models/event.rb
class Event
 
  include Mongoid::Document
  include Geocoder::Model::Mongoid
  include Mongoid::Paperclip

  has_mongoid_attached_file :image, :styles => { :thumb => "100x100#", :small  => "150x150>"}

  field :name, type: String
  field :event_date, type: Date
  field :price, type: String
  field :start_time, type: Time
  field :end_time, type: Time
  field :details, type: String
  field :street, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: String
  field :coordinates, type: Array
  field :updated_by_id, type: String
  field :created_by_id, type: String

  validates_length_of :name, minimum: 4, message: "Please enter a valid event name"
  validates_presence_of :price, message: "Please enter a price (e.g. free, $10.00)"
  validates_length_of :street, minimum: 5, message: "Please enter a valid street address"
  validates_presence_of :city, message: "Please enter a city"
  validates_length_of :state, is: 2, message: "Please enter a valid state"
  validates :zip, length: { is: 5, message: "Zipcode is too short" }, numericality: { only_integer: true, message: "Please enter a valid zip code" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # Combines the four parts of the address that a user submits into one string for Geocoder to change into coordinates
  def address
    self.street + " " + self.city + " " + self.state + " " + self.zip
  end 

  geocoded_by :address
  after_validation :geocode

  belongs_to :event_type
  belongs_to :neighborhood
  belongs_to :location

end

app/models/event_type.rb
class EventType

  include Mongoid::Document

  field :name, type: String

  has_many :events

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	# before_action :authenticate_user
	before_filter :set_timezone

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
 		event_date = params[:event]
 		# Sets one new date using the three different types of input from the form (d, m, y)
		@event.event_date = Date.new event_date["event_date(1i)"].to_i, event_date["event_date(2i)"].to_i, event_date["event_date(3i)"].to_i
		start_time = params[:event]
		# Sets one new time from the two different types of input from the form (h, m)
		# Sets one m, d, y for all new times so that when they are pulled from the db and display as just the time in the view (e.g. 7:00pm), they are sort by time rather than by date (which is listed before the time in the db)
		@event.start_time = Time.new 1900, 1, 1, start_time["start_time(4i)"].to_i, start_time["start_time(5i)"].to_i
		# end_time = params[:event]
		# @event.end_time = Time.new 1900, 1, 1, end_time["end_time(4i)"].to_i, end_time["end_time(5i)"].to_i
		# Stores the user who created the event so that it can be displayed in the view
		if @current_user
			@event.created_by_id = @current_user.name
		end
		if @event.save
			flash[:success] = "Event created"
			redirect_to events_path
		else
			render action: 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

		def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		event_date = params[:event]
		start_time = params[:event]
		end_time = params[:event]
		if @event.update_attributes (event_params)
			# Stores the user who last updated the event so that it can be displayed in the view
			if @current_user
				@event.updated_by_id = @current_user.name
			end
			@event.event_date = Date.new event_date["event_date(1i)"].to_i, event_date["event_date(2i)"].to_i, event_date["event_date(3i)"].to_i
			@event.start_time = Time.new 1900, 1, 1, start_time["start_time(4i)"].to_i, start_time["start_time(5i)"].to_i
			@event.end_time = Time.new 1900, 1, 1, end_time["end_time(4i)"].to_i, end_time["end_time(5i)"].to_i
			@event.save
			flash[:success] = "Event updated"
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Event deleted"
    redirect_to events_path
  end

  def festival
		@festivals = Event.where(event_type_id:("53c303766b656c0da50a0000")).all
  end

  def con
  	@cons = Event.where(event_type_id:("53c303776b656c0da50d0000")).all
  end

  def concert
  	@concerts = Event.where(event_type_id:("53c303776b656c0da50c0000")).all
  end

  def art
  	@arts = Event.where(event_type_id:("53c303776b656c0da50b0000")).all
  end

  protected

  def event_params
  	params.require(:event).permit(:image, :name, :price, :event_type, :neighborhood, :details, :street, :city, :state, :zip, :coordinates, :updated_by_id, :created_by_id)
  end

end

app/views/events/_form.html.erb
<!-- Alerts users if there are any errors in the form -->
<% if @event.errors.any? %>
	<h2><%= pluralize(@event.errors.count, "error") %>
	<ul class="list-group">
		<% @event.errors.messages.each do |message| %>
		<li class="list-group-item list-group-item-danger">
			<%= message[1][0] %>
		</li>
	<% end %>
	</ul> 
<% end %>

<%= bootstrap_form_for @event do |f| %>
<div class="row">
	<!-- Two column form with Bootstrap -->
  <div class="col-md-6">
  	<!-- Makes it easier to style each part of the form with Bootstrap -->
  	<div class="form-group">
			<%= f.text_field :name, placeholder: 'Name', label: "Event Name *" %>
		</div>
  	<div class="form-group">
  		<%= f.label 'Event Type:' %>
  		<%= collection_select :event, :event_type, EventType.all, :id, :name %>
  	</div>
  	<div class="form-group">
			<%= f.date_select :event_date, label: 'Event Date' %>
		</div>
		<!-- Time-field allows you to select hour, minute and AM/PM in one box -->
		<div class="form-inline form-group">
			<%= f.time_select :start_time, {ampm: true, minute_step: 15} %>
			<%= f.time_select :end_time, {ampm: true, minute_step: 15} %>
		</div>
  	<div class="form-group">
			<%= f.text_area :details, {size: "30x7"} %>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
		<%= f.text_field :price, placeholder: 'Price', label: "Price *" %>
		</div>
		<!-- Drop down menu to select neighborhood from neighborhood model -->
  	<div class="form-group">
			<%= f.label "Neighborhood:" %>
			<%= collection_select :event, :neighborhood, Neighborhood.all, :id, :name %>
		</div>
  	<div class="form-group">
			<%= f.text_field :street, placeholder: 'Street Address', label: 'Address *' %>
		</div>
  	<div class="form-group">
			<%= f.text_field :city, placeholder: 'City', label: 'City *' %>
		</div>
  	<div class="form-group">	
			<%= f.text_field :state, :value => 'CA', label: 'State *' %>
		</div>
  	<div class="form-group">
			<%= f.text_field :zip, placeholder: 'Zip Code', label: 'Zip Code *' %>
		</div>
		<%= f.submit "Submit" %>
		<% end %>
		<!-- Back arrow -->
		<span class="spaced glyphicon glyphicon-chevron-left"></span>
		<%= link_to "	Back to the Events Page", events_path %>
	</div>
</div>

app/views/events/art.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default art_nav nav_img"> 
	<%= render partial: "shared/navbar" %>
</nav>

<!-- Flash alerts -->
<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">Art Events</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Timesort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @arts.each do |event| %>
		<tr>
			<td><%= event.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= event.start_time %></td>
			<td><%= event.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= event.name %></strong></td>
			<td class="hidden_col"><%= event.price %></td>
			<td class="hidden_col"><% if event.neighborhood %><%= event.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', event %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

</div>

app/views/events/con.html.erb
<nav class="navbar navbar-default con_nav nav_img">  
	<%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">Geek Events</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Timesort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @cons.each do |event| %>
		<tr>
			<td><%= event.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= event.start_time %></td>
			<td><%= event.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= event.name %></strong></td>
			<td class="hidden_col"><%= event.price %></td>
			<td class="hidden_col"><% if event.neighborhood %><%= event.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', event %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

</div>

app/views/events/concert.html.erb
<nav class="navbar navbar-default concert_nav nav_img">  
	<%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">Concerts</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Timesort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @concerts.each do |event| %>
		<tr>
			<td><%= event.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= event.start_time %></td>
			<td><%= event.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= event.name %></strong></td>
			<td class="hidden_col"><%= event.price %></td>
			<td class="hidden_col"><% if event.neighborhood %><%= event.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', event %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

</div>

app/views/events/edit.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default event_nav nav_img" role="navigation"> 
	<%= render partial: "shared/navbar" %>
</nav>

<div class="container">
	<!-- Flash alerts -->
	<%= render partial: "shared/flash" %>

	<!-- Header specifically for updating event (vs. creating) -->
	<h1 class="header">Update This Event</h1>

	<!-- Form for editing or creating events -->
	<%= render partial: "form" %>
</div>

app/views/events/festival.html.erb
<nav class="navbar navbar-default fest_nav nav_img" role="navigation"> 
	<%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">Festivals</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Timesort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @festivals.each do |event| %>
		<tr>
			<td><%= event.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= event.start_time %></td>
			<td><%= event.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= event.name %></strong></td>
			<td class="hidden_col"><%= event.price %></td>
			<td class="hidden_col"><% if event.neighborhood %><%= event.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', event %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

</div>

app/views/events/index.html.erb
<nav class="navbar navbar-default event_nav nav_img" role="navigation"> 
	<%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">All Events</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Time sort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @events.each do |event| %>
		<tr>
			<td><%= event.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= event.start_time %></td>
			<td><%= event.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= event.name %></strong></td>
			<td class="hidden_col"><%= event.price %></td>
			<td class="hidden_col"><% if event.neighborhood %><%= event.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', event %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

	<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<nav class="navbar navbar-default event_nav nav_img" role="navigation"> 
	<%= render partial: "shared/navbar" %>
</nav>

<div class="container">
	<!-- Flash alert -->
	<%= render partial: "shared/flash" %>

	<!-- Header that is specific to create (vs. update) -->
	<h1 class="header">New Event</h1>

	<!-- Form for create and update -->
	<%= render partial: "form" %>
</div>

app/views/events/show.html.erb
<nav class="navbar navbar-default event_nav nav_img" role="navigation"> 
  <%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class="container">
  <h1 class="header"><%= @event.name %></h1>
  <div class="row show_text">
    <!-- Two column layout with Bootstrap -->
    <div class="col-md-6 show_col_1">
      <!-- Back arrow and link to the main art events page -->
      <span class="glyphicon glyphicon-chevron-left"></span>
      <%= link_to " Back to the Events Page", events_path %>
      <br><br>
      <p class="bold inline">Date:  </p>
      <%= @event.event_date.strftime("%m/%d/%y")%>
      <br><br>
      <p class="bold inline">Time:  </p>
      <%= @event.start_time.strftime("%l:%M%p") %> - <%= @event.end_time.strftime("%l:%M%p") %>
      <br><br>
      <p class="bold">Address:</p> 
      <%= @event.street %>, <%= @event.city %>, <%= @event.state %>, <%= @event.zip %>
      <br><br>
      <% if @event.details != "" %>
        <p class="bold">Details:</p>
        <%= @event.details %>
      <% end %>
      <br><br>
      <!-- If the event has been updated at some point, it will show the username of the last person who updated it -->
      <% if @event.updated_by_id != nil %>
        <em>Last updated by:</em>
        <%= @event.updated_by_id %>
      <% end %>
      <!-- For styling purposes, only shows the ~ if both Last Updated by and Created by are being shown -->
      <!-- Otherwise there is nothing or only one of them on the line -->
      <% if @event.updated_by_id != nil && @event.created_by_id != nil %>
        ~ 
      <% end %>
      <!-- If someone created this event (not seeded), their username will be displayed here -->
      <% if @event.created_by_id != nil %>
        <em>Created by:</em> 
        <%= @event.created_by_id %>
      <% end %>
      <br><br>
      <%= link_to "Update This Event", edit_event_path(@event) %>
      <br><br>
      <!-- Hides the delete button unless user is the admin -->
      <% if current_user %>
        <% if current_user.is_admin? %>
          <%= link_to "Delete This Event", @event, method: :delete, data: { confirm: 'Are you sure you want to delete this event?' } %>
        <% end %>
      <% end %>
    </div>
    <!-- Second column -->
    <div class="col-md-6" style='width: 400px;'>
      <div id="map" style='width: 400px; height: 400px;'></div>
    </div>
  
  <!-- Google Maps API -->
  <script type ="text/javascript">
  	var handler = Gmaps.build('Google');
    // Sets the zoom, your API key
    handler.buildMap({ provider: {zoom: 14, provider_key: "AIzaSyBnugBXbtHJ6qqIyILKqKPQ1l2rafKtjx0"}, internal: {id: 'map'}}, function(){
    // Adds markers to the event based on the coordinates that Geocoder made with the art event's combined address
    // Latitude and longitude are reversed in the Mongo db
    markers = handler.addMarker(
      {
        lat: <%= @event.to_coordinates[0] %>,
        lng: <%= @event.to_coordinates[1] %>
      }
    );
    // Tells the map to center on those coordinates
    handler.map.centerOn({
        lat: <%= @event.to_coordinates[0] %>,
        lng: <%= @event.to_coordinates[1] %>
      });
  });
  </script>
</div>