config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :events
  get '/festivals', to: 'events#festival', as: 'festivals'
  get '/arts', to: 'events#art', as: 'arts'
  get '/cons', to: 'events#con', as: 'cons'
  get '/concerts', to: 'events#concert', as: 'concerts'
  resources :users, only: [:new, :create]

  root 'events#index'

end

app/views/cons/index.html.erb
<nav class="navbar navbar-default con_nav nav_img">  
	<%= render partial: "shared/navbar" %>
</nav>

<%= render partial: "shared/flash" %>

<div class= "container">
	<h1 class="header index_header">Geek Events</h1>
	<br>
	<table class="events_list table table-bordered table-responsive table-condensed table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th style="display: none">Timesort</th>
			<th>Time</th>
			<th>Name</th>
			<th class="hidden_col">Price</th>
			<th class="hidden_col">Neighborhood</th>
			<th>More Info</th>
		</tr>
		</thead>
		<tbody>
		<% @cons.each do |con| %>
		<tr>
			<td><%= con.event_date.strftime("%m/%d/%y") %></td>
			<td style="display: none"><%= con.start_time %></td>
			<td><%= con.start_time.strftime("%l:%M%P") %></td>
			<td><strong><%= con.name %></strong></td>
			<td class="hidden_col"><%= con.price %></td>
			<td class="hidden_col"><% if con.neighborhood %><%= con.neighborhood.name %><% end %></td>
			<td><%= link_to 'Details', con %></td>
		</tr>
		<% end %>
		</tbody>
	</table>

	<%= link_to 'New Geek Event', new_con_path %>
</div>